--[[ Writes docs/CATALOGUE.md from the engine's own tables and output, so it
     cannot drift from what the script does. tools/test.sh fails when the
     committed copy is stale.

       lua5.4 tools/catalogue_md.lua > docs/CATALOGUE.md
]]

local HERE = (arg and arg[0] or ""):match("^(.*)[/\\]") or "."
local R = HERE .. "/../reascripts/"
local T = dofile(R .. "mc_theory.lua")
local O = dofile(R .. "mc_orchestra.lua")
local C = dofile(R .. "mc_catalogue.lua").init(T, O)

local out = {}
local function w(s) out[#out + 1] = s or "" end

w("# The catalogue")
w()
w("Generated by `tools/catalogue_md.lua` from the engine itself. Do not edit by hand.")
w()
w("Nothing in the catalogue is stored. Every entry below is calculated when it is")
w("asked for, from the scale, the chords, the instrument and the register, then")
w("checked the way a player would check it. The lists here are what that makes")
w("for one reference setting: **C major, I-V-vi-IV, four bars of 4/4 at 120 bpm,")
w("middle register**. Change any of those and the notes change with it, and so,")
w("sometimes, does what is left out.")
w()

-- The reference matrix.
local types = {}
for _, c in ipairs(C.CATEGORIES) do for _, t in ipairs(c.types) do types[#types + 1] = t end end

w("## How many entries each instrument gets")
w()
w("`-` is a type the instrument does not play (the window says why). Sections play")
w("harmony only.")
w()
local head = { "| |" }
local rule = { "| --- |" }
for _, t in ipairs(types) do head[#head + 1] = " " .. t .. " |"; rule[#rule + 1] = " ---: |" end
w(table.concat(head)); w(table.concat(rule))
local function row(name, ctx)
  local cells = { "| " .. name .. " |" }
  for _, t in ipairs(types) do
    local cell
    if ctx.ensemble and C.categoryOf(t) ~= "Harmony" then cell = ""
    else
      local r = C.catalogue(ctx, t)
      cell = r.avoided and "-" or tostring(#r.entries)
    end
    cells[#cells + 1] = " " .. cell .. " |"
  end
  w(table.concat(cells))
end
for _, inst in ipairs(O.INSTRUMENTS) do
  row(inst.name, C.context({ root = 1, scale = 1, prog = "I-V-vi-IV", inst = inst.id }))
end
for _, e in ipairs(O.ENSEMBLES) do
  row(e.name, C.context({ root = 1, scale = 1, prog = "I-V-vi-IV", inst = "pno", ensemble = e.id }))
end
w()

-- Every type, with its entries as the piano has them and what a melodic
-- instrument loses.
local pno = C.context({ root = 1, scale = 1, prog = "I-V-vi-IV", inst = "pno" })
local vln = C.context({ root = 1, scale = 1, prog = "I-V-vi-IV", inst = "vln1" })
local tuba = C.context({ root = 1, scale = 1, prog = "I-V-vi-IV", inst = "tuba" })
for _, cat in ipairs(C.CATEGORIES) do
  w("## " .. cat.name)
  w()
  for _, t in ipairs(cat.types) do
    local r = C.catalogue(pno, t)
    w("### " .. t)
    w()
    w(("%d entries on the piano, %d on Violin I, %d on the tuba."):format(#r.entries,
      #C.catalogue(vln, t).entries, #C.catalogue(tuba, t).entries))
    w()
    for _, e in ipairs(r.entries) do
      w(("- **%s** (%s) - %s"):format(e.label, e.band:lower(), e.hint))
    end
    local hidden = C.catalogue(tuba, t).hidden
    if #hidden > 0 then
      w()
      local why = {}
      for _, h in ipairs(hidden) do why[#why + 1] = h.count .. " " .. h.reason end
      w("Left out on the tuba: " .. table.concat(why, "; ") .. ".")
    end
    w()
  end
end

w("## The chords")
w()
w("Any of these can sit on any degree of the scale, chained up to " .. T.MAX_CHAIN .. " at a time. The")
w("diatonic ones are built from the scale itself; the rest are Starting Blocks' table,")
w("on the degree's root. Under a chord with notes the scale lacks, the scale bends to")
w("meet it for as long as it lasts.")
w()
w("| family | chord | name | semitones |")
w("| --- | --- | --- | --- |")
for _, d in ipairs(T.DIATONIC) do
  local off = {}
  for i, o in ipairs(d.offsets) do off[i] = o end
  w(("| Diatonic | %s | built from the scale | steps %s |"):format(d.name, table.concat(off, " ")))
end
for _, c in ipairs(T.CHORDS) do
  w(("| %s | %s | %s | %s |"):format(T.FAMILIES[c.fam], c.sym, c.name, table.concat(c.iv, " ")))
end
w()

w("## The instruments")
w()
w("Sounding pitches. `sweet` is where the catalogue writes; `fast` is the shortest")
w("time between two notes it plays cleanly; `leap` the widest leap it takes in")
w("passing.")
w()
w("| | range | sweet | voice | at once | fast | leap | breathes |")
w("| --- | --- | --- | --- | ---: | ---: | ---: | --- |")
for _, i in ipairs(O.INSTRUMENTS) do
  w(("| %s | %s-%s | %s-%s | %s | %d | %.2fs | %d | %s |"):format(i.name,
    T.pitchName(i.low), T.pitchName(i.high), T.pitchName(i.sweet[1]), T.pitchName(i.sweet[2]),
    i.role, i.poly, i.fast, i.leap, i.breath and "yes" or ""))
end
w()
local avoids = {}
for _, i in ipairs(O.INSTRUMENTS) do
  if i.avoid then
    local keys = {}
    for k in pairs(i.avoid) do keys[#keys + 1] = k end
    table.sort(keys)
    for _, k in ipairs(keys) do avoids[#avoids + 1] = ("- **%s**, %s: %s."):format(i.name, k, i.avoid[k]) end
  end
end
w("What each instrument does not play, and why:")
w()
for _, a in ipairs(avoids) do w(a) end
w()
w("## The sections")
w()
for _, e in ipairs(O.ENSEMBLES) do
  local parts = {}
  for _, p in ipairs(e.parts) do
    parts[#parts + 1] = p.name .. " (voice " .. p.voice .. (p.octave and ", an octave down" or "") .. ")"
  end
  w(("- **%s**: %s"):format(e.name, table.concat(parts, ", ")))
end
w()

io.write(table.concat(out, "\n"))
